### ISSUE TITLE
User choice (--color never | --color always) has no effect?

### ISSUE THREAD

**Issue by mfilteau** [rust-cli/concolor#19]
When calling the program below with `cargo run -- --color never help`, the help text is still colored.

I would have expected that concolor_clap::color_choice() would have returned the user's desired choice.

When executing `cargo run -- --color never add`, I get:

```
Cli { color: Color { color: Never }, action: Add }
Always
```

```rust
use clap::Parser;

/// Checking that --color works
#[derive(Debug, clap::Parser)]
#[clap(color = concolor_clap::color_choice())]
struct Cli {
    #[command(flatten)]
    color: concolor_clap::Color,

    #[command(subcommand)]
    action: Action,
}

#[derive(Debug, clap::Subcommand)]
enum Action {
   Add,
   Remove,
}

fn main() {
    let cli = Cli::parse();
    println!("{:?}", cli);
    println!("{:?}", concolor_clap::color_choice());
}
```

Am I missing something?

**Comment by epage** [comment]
> When calling the program below with cargo run -- --color never help, the help text is still colored.

The `help` command is being processed during `Cli::parse();` but `clap` has no knowledge of `concolor_clap::Color`, so it can't use it.  All it can make decisions off of is the environment when you set `#[clap(color = concolor_clap::color_choice())]`.

If you want `--color` to apply to `--help`, you'll need to implement the `help` subcommand yourself.  In clap 4, when you call `cmd.render_help` (you can get `cmd` from `Cli` via `CommandFactor::command`), you'll get an ANSI colored value.  You can then do processing of that on your side.  I'm working on building up tools for that processing which will make this easier.

As this is working as expected, I'm going to close this.

**Comment by mfilteau** [comment]
It makes sense. Thanks a lot!
