### ISSUE TITLE
Should we allow setting color for different streams separately?

### ISSUE THREAD

**Issue by pksunkara** [rust-cli/concolor#29]
Is there a case where people want to enable color for stderr but disable it for stdout?

If yes, how would the command line options UX be for a cli to allow the end users to configure this?

**Comment by epage** [comment]
The cases I can think of
- Piping both, one will go to `less`, needing to be forced, and the other will go to a file and wanting it to remain disabled
- The application's ux is different enough for stdout/stderr that the application wants to (ab)use concolor for controlling its UX

If people can think of more, we can add it to the list.

**Comment by epage** [comment]
For me, the cases don't seem compelling enough to deal with the complexity.

Instead, I've been wondering if `CLICOLOR_FORCE` /  `--color=always` should still cause the terminal's capabilities to be queried (truecolor, 256color, 16color) or if they should force a specific version of the modes.

**Comment by pksunkara** [comment]
How do I move this issue to anstyle?

**Comment by epage** [comment]
Without an end-user with a use case for it, I personally wouldn't bother.
