### ISSUE TITLE
Is expected that older versions read different globals?

### ISSUE THREAD

**Issue by Zheoni** [rust-cli/concolor#32]
Hi, when I use a library that depends on `v0.0.11` the global value that I set in my application has no effect. Only if the library also uses `v0.1.0` (same as the binary) the globals are shared between the aplication and the library.

I tested this having 2 identical libs in a workspace with only this function. One with `concolor` `v0.0.11` (or `v0.0.12`) and the other with `v0.1.0`.

```rust
pub fn has_color() -> bool {
    concolor::get(concolor::Stream::Stderr).color()
}
```

Then I call these functions from binary that depends on those libs and only the new version stays in sync. (I can upload a test repo but honestly it's just 10 lines of code)

Is this expected before 1.0? If so, it would be great to mention it in the readme to avoid confusion.

**Comment by epage** [comment]
This is why the feature name for using the global was named `api_unstable`, it required keeping everything in lockstep with each other and so any version upgrade could be a breaking change.

With splitting out `concolor_override`, we have a fairly safe path forward for compatibility so we can keep one instance of this global that all crates talk so we can avoid this problem in the future.  This allowed dropping the `_unstable` suffix and why I felt like I could move the version numbers outside of `0.0.x`
