### ISSUE TITLE
crates.io has v0.0.8, repo has tags for v0.0.9 and v0.0.10

### ISSUE THREAD

**Issue by dkg** [rust-cli/concolor#9]
Is there a reason that the repository on github has these newer tags but they have not been released to crates.io?

**Comment by epage** [comment]
There are multiple crates within the repo

Breaking down the tags by crate:
- concolor the primary API
  - 0.0.8
- concolor-query: lower level API
  - 0.0.5
  - ...
- concolor-clap: clap integration for the primary API
  - 0.0.10
  - 0.0.9
  - 0.0.8
  - ...
